site_name: Dogshow app description
nav:
  - Home: index.md
  - Api:
      - "experts/<id>": experts.md
      - "/participants/<id>": participants.md
      - "/participant_ring/<id>": participant_ring.md
      - "/club_breeds/<id>": club_breeds.md
      - "/dismissed_count/<id>": dismissed_count.md
      - "/breed_experts/": breed_experts.md
      - "/breeds_count/": breed_count.md
      - "/report/<year>": report.md

theme:
  name: material
