# Generated by Django 3.2.9 on 2022-06-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_participant_previous_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='club_members', to='main.Participant'),
        ),
    ]
