version: '3'

services:
  back:
    container_name: dogs_back
    build: ./back
    command: bash -c "
      python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000";
    ports:
      - '8000:8000'
    depends_on:
      - db

  front:
    container_name: dogs_front
    build: ./front/dog_front
    ports:
      - '8080:8080'
    depends_on:
      - back

  db:
    container_name: dogs_db
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pg_admin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@user.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  pgdata:
